package com.tamersarioglu.kykscraped.domain.model

data class City(
    val name: String,
    val code: String
)

object Cities {
    val list = listOf(
        City("Adana", "Adana"),
        City("Adıyaman", "Adiyaman"),
        City("Afyonkarahisar", "Afyonkarahisar"),
        City("Ağrı", "Agri"),
        City("Amasya", "Amasya"),
        City("Ankara", "Ankara"),
        City("Antalya", "Antalya"),
        City("Artvin", "Artvin"),
        City("Aydın", "Aydin"),
        City("Balıkesir", "Balikesir"),
        City("Bilecik", "Bilecik"),
        City("Bingöl", "Bingol"),
        City("Bitlis", "Bitlis"),
        City("Bolu", "Bolu"),
        City("Burdur", "Burdur"),
        City("Bursa", "Bursa"),
        City("Çanakkale", "Canakkale"),
        City("Çankırı", "Cankiri"),
        City("Çorum", "Corum"),
        City("Denizli", "Denizli"),
        City("Diyarbakır", "Diyarbakir"),
        City("Düzce", "Duzce"),
        City("Edirne", "Edirne"),
        City("Elazığ", "Elazig"),
        City("Erzincan", "Erzincan"),
        City("Erzurum", "Erzurum"),
        City("Eskişehir", "Eskisehir"),
        City("Gaziantep", "Gaziantep"),
        City("Giresun", "Giresun"),
        City("Gümüşhane", "Gumushane"),
        City("Hakkari", "Hakkari"),
        City("Hatay", "Hatay"),
        City("Iğdır", "Igdir"),
        City("Isparta", "Isparta"),
        City("İstanbul", "Istanbul"),
        City("İzmir", "Izmir"),
        City("Kahramanmaraş", "Kahramanmaras"),
        City("Karabük", "Karabuk"),
        City("Karaman", "Karaman"),
        City("Kars", "Kars"),
        City("Kastamonu", "Kastamonu"),
        City("Kayseri", "Kayseri"),
        City("Kırıkkale", "Kirikkale"),
        City("Kırklareli", "Kirklareli"),
        City("Kırşehir", "Kirsehir"),
        City("Kilis", "Kilis"),
        City("Kocaeli", "Kocaeli"),
        City("Konya", "Konya"),
        City("Kütahya", "Kutahya"),
        City("Malatya", "Malatya"),
        City("Manisa", "Manisa"),
        City("Mardin", "Mardin"),
        City("Mersin", "Mersin"),
        City("Muğla", "Mugla"),
        City("Muş", "Mus"),
        City("Nevşehir", "Nevsehir"),
        City("Niğde", "Nigde"),
        City("Ordu", "Ordu"),
        City("Osmaniye", "Osmaniye"),
        City("Rize", "Rize"),
        City("Sakarya", "Sakarya"),
        City("Samsun", "Samsun"),
        City("Şanlıurfa", "Sanliurfa"),
        City("Siirt", "Siirt"),
        City("Sinop", "Sinop"),
        City("Şırnak", "Sirnak"),
        City("Sivas", "Sivas"),
        City("Tekirdağ", "Tekirdag"),
        City("Tokat", "Tokat"),
        City("Trabzon", "Trabzon"),
        City("Tunceli", "Tunceli"),
        City("Şanlıurfa", "Sanliurfa"),
        City("Uşak", "Usak"),
        City("Van", "Van"),
        City("Yalova", "Yalova"),
        City("Yozgat", "Yozgat"),
        City("Zonguldak", "Zonguldak")
    )
} 